### PR TITLE
[SLE-12-SP5] Set crypto_hash as "sha1" and set crypto_cipher as "aes256" and other changes

### PR DESCRIPTION
**Pull request by liangxin1300**
## Problem

- [*bsc#1204530*](https://bugzilla.suse.com/show_bug.cgi?id=1204530)
On SLE12SP5, after using yast2-cluster, both `crypto_hash` and `crypto_cipher` are `none` , and if the node is in the cloud environment, crmsh bootstrap will configure `udpu`, instead of `udp` when using yast2-cluster
- yast2-cluster will load `corosync.conf.example` when firstly running, the values from it might be invalid, should be dropped
- After dropped loadding `corosync.conf.example`, when configuring with mcast, the value of `mcastaddr` `mcastport` and `bindnetaddr` are missing
- Set focus on "Generate Auth Key File" when secauth is true
- Implement ValidateSecurity method
- Set focus on memberaddr add when using udpu

### CODE REVIEW

**Comment by liangxin1300** [comment]
Hi @lslezak,

Could you please take a look at this PR? Thanks!

**Comment by varkoly** [comment]
Looks good for me

**Comment by liangxin1300** [comment]
SLE15+ has the similar problem.
Since the python code is using python3 in SLE15+ instead of python2 here in SLE12SP5, I will create a new PR

**Comment by liangxin1300** [comment]
please hold on to merge

**Review by varkoly — APPROVED** [review]
Thanks! LGTM

**Pull request merged**
